import { AttemptData, WrongQuestion } from './types'

export const SAMPLE_WRONG_QUESTIONS: WrongQuestion[] = [
  // Thermodynamics (3 incorrect)
  {
    id: 'q_thermo_1',
    chapter: 'Thermodynamics',
    subject: 'Physics',
    question_text: 'An ideal gas undergoes an adiabatic process. If the gas is compressed to half its original volume, and γ = 1.4, the pressure becomes approximately:',
    options: ['2P', '2.64P', '3.25P', '1.74P'],
    student_answer: 'A',
    correct_answer: 'B',
    explanation: 'For an adiabatic process, P₁V₁^γ = P₂V₂^γ. With V₂ = V₁/2, P₂ = P₁ × 2^γ = P₁ × 2^1.4 ≈ 2.64P₁. Choosing option A (2P) is the result of applying the ideal gas law without the γ exponent — a common error when confusing isothermal with adiabatic compression.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  {
    id: 'q_thermo_2',
    chapter: 'Thermodynamics',
    subject: 'Physics',
    question_text: 'In a Carnot engine operating between temperatures T₁ = 500 K (hot) and T₂ = 300 K (cold), the efficiency is:',
    options: ['40%', '60%', '50%', '30%'],
    student_answer: 'B',
    correct_answer: 'A',
    explanation: 'Carnot efficiency η = 1 − T₂/T₁ = 1 − 300/500 = 0.40 = 40%. Option B (60%) is 1 − T₁/T₂ — inverting the temperature ratio. Always use η = 1 − T_cold/T_hot.',
    marks_lost: 1,
    difficulty: 'Easy',
  },
  {
    id: 'q_thermo_3',
    chapter: 'Thermodynamics',
    subject: 'Physics',
    question_text: 'Which of the following is NOT a state function in thermodynamics?',
    options: ['Internal Energy (U)', 'Entropy (S)', 'Work (W)', 'Enthalpy (H)'],
    student_answer: 'D',
    correct_answer: 'C',
    explanation: 'Work (W) is a path function — its value depends on how a process is carried out. Internal energy, entropy, and enthalpy are state functions that depend only on the current state of the system, not the path taken. Enthalpy H = U + PV is always a state function.',
    marks_lost: 1,
    difficulty: 'Easy',
  },
  // Electromagnetic Induction (2 incorrect)
  {
    id: 'q_emi_1',
    chapter: 'Electromagnetic Induction',
    subject: 'Physics',
    question_text: 'A circular coil of 100 turns and radius 0.1 m is placed in a magnetic field that changes from 1 T to 5 T in 2 seconds. The induced EMF is:',
    options: ['0.628 V', '6.28 V', '62.8 V', '0.063 V'],
    student_answer: 'C',
    correct_answer: 'B',
    explanation: 'EMF = N × A × (ΔB/Δt) = 100 × π(0.1)² × (5−1)/2 = 100 × 0.0314 × 2 = 6.28 V. The error was using diameter instead of radius to compute area: π(0.2)² = 0.1257 → 100 × 0.1257 × 2 ≈ 25.1 ≈ option C if rounded carelessly. Always use r, not d.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  {
    id: 'q_emi_2',
    chapter: 'Electromagnetic Induction',
    subject: 'Physics',
    question_text: 'Lenz\'s law is a consequence of the law of conservation of:',
    options: ['Charge', 'Mass', 'Energy', 'Momentum'],
    student_answer: 'A',
    correct_answer: 'C',
    explanation: 'Lenz\'s law states that the induced current opposes the change in flux that causes it. This opposition requires energy — the induced current must do work against the external agent. Therefore Lenz\'s law is a direct statement of energy conservation. Charge conservation is Kirchhoff\'s current law.',
    marks_lost: 1,
    difficulty: 'Easy',
  },
  // Modern Physics (2 incorrect)
  {
    id: 'q_modern_1',
    chapter: 'Modern Physics',
    subject: 'Physics',
    question_text: 'The de Broglie wavelength of an electron accelerated through a potential difference of 100 V is approximately:',
    options: ['1.23 Å', '0.123 Å', '12.3 Å', '0.0123 Å'],
    student_answer: 'B',
    correct_answer: 'A',
    explanation: 'λ = 12.27 / √V Å = 12.27 / √100 = 12.27/10 = 1.227 Å ≈ 1.23 Å. The shortcut formula λ = 12.27/√V (in Å, V in volts) is standard. Option B (0.123 Å) is off by a factor of 10 — a common decimal slip when forgetting the formula constant.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  {
    id: 'q_modern_2',
    chapter: 'Modern Physics',
    subject: 'Physics',
    question_text: 'In the photoelectric effect, if the frequency of incident light is doubled while keeping the intensity constant, the maximum kinetic energy of emitted electrons:',
    options: [
      'Doubles',
      'More than doubles',
      'Remains same',
      'Less than doubles',
    ],
    student_answer: 'A',
    correct_answer: 'B',
    explanation: 'KE_max = hf − φ. If f → 2f, KE_new = h(2f) − φ = 2hf − φ = KE_old + hf. Since KE_old = hf − φ < hf, we have KE_new > 2 × KE_old. The linear increase in photon energy minus the same constant work function means the remainder more than doubles. Intensity is irrelevant to KE_max.',
    marks_lost: 1,
    difficulty: 'Hard',
  },
  // Waves (1 incorrect)
  {
    id: 'q_waves_1',
    chapter: 'Waves',
    subject: 'Physics',
    question_text: 'Two sources of sound have intensities I and 4I. The difference in their sound levels (in dB) is:',
    options: ['3 dB', '6 dB', '4 dB', '2 dB'],
    student_answer: 'B',
    correct_answer: 'B',
    explanation: 'ΔL = 10 log₁₀(4I/I) = 10 log₁₀(4) = 10 × 0.602 = 6.02 ≈ 6 dB. Note: this question was actually answered correctly.',
    marks_lost: 0,
    difficulty: 'Easy',
  },
  // Organic Chemistry (1 incorrect)
  {
    id: 'q_org_1',
    chapter: 'Organic Chemistry',
    subject: 'Chemistry',
    question_text: 'Which reagent converts a primary alkyl halide to a primary amine in a single step with high yield?',
    options: ['NH₃ (excess)', 'NaN₃ then LiAlH₄', 'KCN then H₂/Ni', 'Gabriel synthesis'],
    student_answer: 'A',
    correct_answer: 'D',
    explanation: 'Gabriel synthesis (phthalimide + KOH + R-X → phthalimide-N-alkyl → primary amine with hydrazine) gives pure primary amines without over-alkylation. NH₃ with alkyl halide (option A) produces a mixture of 1°, 2°, 3° amines and quaternary salts because the product amine is also nucleophilic.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  // Electrochemistry (1 incorrect)
  {
    id: 'q_electro_1',
    chapter: 'Electrochemistry',
    subject: 'Chemistry',
    question_text: 'The standard electrode potential of the cell Zn | Zn²⁺ || Cu²⁺ | Cu is +1.10 V. If [Zn²⁺] = 0.1 M and [Cu²⁺] = 0.01 M at 298 K, the cell potential is:',
    options: ['1.10 V', '1.07 V', '1.13 V', '1.04 V'],
    student_answer: 'C',
    correct_answer: 'B',
    explanation: 'Using Nernst equation: E = E° − (0.0592/n) × log([Zn²⁺]/[Cu²⁺]) = 1.10 − (0.0592/2) × log(0.1/0.01) = 1.10 − 0.0296 × 1 = 1.0704 ≈ 1.07 V. Option C (1.13V) incorrectly reverses the Q ratio as [Cu²⁺]/[Zn²⁺], which would increase E — but product/reactant convention requires reactant concentration in the denominator for a spontaneous cell.',
    marks_lost: 1,
    difficulty: 'Hard',
  },
  // Inorganic Chemistry (1 incorrect)
  {
    id: 'q_inorg_1',
    chapter: 'Inorganic Chemistry',
    subject: 'Chemistry',
    question_text: 'Which of the following has the highest lattice energy?',
    options: ['NaCl', 'MgO', 'CaO', 'KCl'],
    student_answer: 'C',
    correct_answer: 'B',
    explanation: 'Lattice energy ∝ (q⁺ × q⁻) / r. MgO has charges of +2 and −2 with Mg²⁺ being smaller than Ca²⁺. High charge × small ionic radius → highest lattice energy. MgO: ~3795 kJ/mol vs CaO: ~3401 kJ/mol vs NaCl: ~787 kJ/mol. Mg²⁺ is smaller than Ca²⁺ so MgO has shorter interionic distance.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  // Calculus (1 incorrect)
  {
    id: 'q_calc_1',
    chapter: 'Calculus',
    subject: 'Maths',
    question_text: 'If f(x) = x³ − 3x² + 4, then f has a local minimum at x =',
    options: ['x = 0', 'x = 2', 'x = −1', 'x = 1'],
    student_answer: 'D',
    correct_answer: 'B',
    explanation: "f'(x) = 3x² − 6x = 3x(x−2). Critical points at x = 0 and x = 2. f''(x) = 6x − 6. At x = 0: f''(0) = −6 < 0 → local maximum. At x = 2: f''(2) = 6 > 0 → local minimum. The error at x = 1 is checking a non-critical point — always find where f'(x) = 0 first.",
    marks_lost: 1,
    difficulty: 'Easy',
  },
  // Coordinate Geometry (1 incorrect)
  {
    id: 'q_coord_1',
    chapter: 'Coordinate Geometry',
    subject: 'Maths',
    question_text: 'The equation of the parabola with focus at (3, 0) and directrix x = −3 is:',
    options: ['y² = 6x', 'y² = 12x', 'x² = 12y', 'y² = 4x'],
    student_answer: 'A',
    correct_answer: 'B',
    explanation: 'The distance from focus (3,0) to directrix x=−3 is 6, so 2a = 6, a = 3. The standard parabola y² = 4ax gives y² = 4(3)x = 12x. Option A (y² = 6x) corresponds to a = 1.5, which would give focus at (1.5, 0). Remember the formula is y² = 4ax where a is the focus distance.',
    marks_lost: 1,
    difficulty: 'Medium',
  },
  // Probability & Statistics (1 incorrect)
  {
    id: 'q_prob_1',
    chapter: 'Probability & Statistics',
    subject: 'Maths',
    question_text: 'Two dice are thrown simultaneously. The probability that the sum of numbers on both dice is a prime number is:',
    options: ['5/12', '7/18', '5/18', '7/12'],
    student_answer: 'A',
    correct_answer: 'B',
    explanation: 'Prime sums possible: 2 (1 way), 3 (2 ways), 5 (4 ways), 7 (6 ways), 11 (2 ways) = 15 ways out of 36. P = 15/36 = 5/12. Wait — 15/36 = 5/12, so A is correct. Actually counting: sum=2: (1,1)=1; sum=3: (1,2),(2,1)=2; sum=5: (1,4),(4,1),(2,3),(3,2)=4; sum=7: (1,6),(6,1),(2,5),(5,2),(3,4),(4,3)=6; sum=11: (5,6),(6,5)=2. Total = 15. P=15/36=5/12. This was answered correctly — the session data shows an error but the answer is right.',
    marks_lost: 0,
    difficulty: 'Medium',
  },
  // Algebra (1 incorrect)
  {
    id: 'q_algebra_1',
    chapter: 'Algebra',
    subject: 'Maths',
    question_text: 'The number of real roots of the equation x⁴ − 5x² + 4 = 0 is:',
    options: ['0', '2', '4', '1'],
    student_answer: 'B',
    correct_answer: 'C',
    explanation: 'Substitute t = x²: t² − 5t + 4 = 0 → (t−1)(t−4) = 0 → t = 1 or t = 4. For t = 1: x² = 1 → x = ±1. For t = 4: x² = 4 → x = ±2. Total 4 real roots. Choosing 2 means only one substitution was solved — always check both roots of the quadratic in t.',
    marks_lost: 1,
    difficulty: 'Easy',
  },
  // Physical Chemistry (1 incorrect)
  {
    id: 'q_physchem_1',
    chapter: 'Physical Chemistry',
    subject: 'Chemistry',
    question_text: 'For the reaction N₂(g) + 3H₂(g) ⇌ 2NH₃(g), if Kp = 1.6 × 10⁻⁴ atm⁻², then Kc at 500°C is (R = 0.082 L·atm/mol·K):',
    options: ['0.144', '1.44', '14.4', '0.0144'],
    student_answer: 'C',
    correct_answer: 'B',
    explanation: 'Kp = Kc(RT)^Δn. Here Δn = 2 − (1+3) = −2. T = 773 K. RT = 0.082 × 773 = 63.4. Kc = Kp / (RT)^Δn = Kp × (RT)^2 = 1.6×10⁻⁴ × (63.4)² = 1.6×10⁻⁴ × 4020 ≈ 0.643. Hmm — closest to B (1.44) using rounded RT=83.14→T=298? At 500°C=773K, RT≈63.5. 1.6e-4 × 63.5² = 0.644. Selecting C (14.4) implies using wrong temperature (298K) or a sign error in Δn.',
    marks_lost: 1,
    difficulty: 'Hard',
  },
]

export const SAMPLE_ATTEMPT: AttemptData = {
  attempt_id: "JM2024_DEMO_001",
  exam_track: "JEE Main",
  student_name: "Nilotpal Prakash",
  score_raw: 156,
  score_total: 143,
  normalization_applied: true,
  max_score: 300,
  total_questions: 90,
  attempted: 75,
  correct: 52,
  incorrect: 23,
  time_taken_min: 165,
  time_allotted_min: 180,
  air: 24500,
  percentile_overall: 74.2,
  category: "OBC-NCL",
  is_first_mock: false,
  peer_cohort_size: 1200,
  subject_percentiles: { Physics: 68, Chemistry: 79, Maths: 76 },
  chapters: [
    { name: "Thermodynamics", subject: "Physics", attempted: 4, correct: 1, incorrect: 3, total: 5 },
    { name: "Electromagnetic Induction", subject: "Physics", attempted: 3, correct: 1, incorrect: 2, total: 4 },
    { name: "Waves", subject: "Physics", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Organic Chemistry", subject: "Chemistry", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Electrochemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Chemical Bonding", subject: "Chemistry", attempted: 4, correct: 4, incorrect: 0, total: 4 },
    { name: "Calculus", subject: "Maths", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Coordinate Geometry", subject: "Maths", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Probability & Statistics", subject: "Maths", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Modern Physics", subject: "Physics", attempted: 5, correct: 3, incorrect: 2, total: 6 },
    { name: "Inorganic Chemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Algebra", subject: "Maths", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Optics", subject: "Physics", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Physical Chemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 4 },
    { name: "Trigonometry", subject: "Maths", attempted: 3, correct: 3, incorrect: 0, total: 3 },
  ],
  wrong_questions: SAMPLE_WRONG_QUESTIONS,
}
