import { AttemptData } from './types'

export const SAMPLE_ATTEMPT: AttemptData = {
  attempt_id: "JM2024_DEMO_001",
  exam_track: "JEE Main",
  student_name: "Arjun Kumar",
  score_raw: 156,
  score_total: 143,
  normalization_applied: true,
  max_score: 300,
  total_questions: 90,
  attempted: 75,
  correct: 52,
  incorrect: 23,
  time_taken_min: 165,
  time_allotted_min: 180,
  air: 24500,
  percentile_overall: 74.2,
  category: "OBC-NCL",
  is_first_mock: false,
  peer_cohort_size: 1200,
  subject_percentiles: { Physics: 68, Chemistry: 79, Maths: 76 },
  chapters: [
    { name: "Thermodynamics", subject: "Physics", attempted: 4, correct: 1, incorrect: 3, total: 5 },
    { name: "Electromagnetic Induction", subject: "Physics", attempted: 3, correct: 1, incorrect: 2, total: 4 },
    { name: "Waves", subject: "Physics", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Organic Chemistry", subject: "Chemistry", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Electrochemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Chemical Bonding", subject: "Chemistry", attempted: 4, correct: 4, incorrect: 0, total: 4 },
    { name: "Calculus", subject: "Maths", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Coordinate Geometry", subject: "Maths", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Probability & Statistics", subject: "Maths", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Modern Physics", subject: "Physics", attempted: 5, correct: 3, incorrect: 2, total: 6 },
    { name: "Inorganic Chemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 5 },
    { name: "Algebra", subject: "Maths", attempted: 5, correct: 4, incorrect: 1, total: 6 },
    { name: "Optics", subject: "Physics", attempted: 3, correct: 2, incorrect: 1, total: 4 },
    { name: "Physical Chemistry", subject: "Chemistry", attempted: 4, correct: 3, incorrect: 1, total: 4 },
    { name: "Trigonometry", subject: "Maths", attempted: 3, correct: 3, incorrect: 0, total: 3 },
  ],
}
